version: '3.8'

services:
  sipgateway:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=mysql://sipgateway_user:sipgateway_password@mysql:3306/sipgateway
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - sipgateway-network

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password_here
      MYSQL_DATABASE: sipgateway
      MYSQL_USER: sipgateway_user
      MYSQL_PASSWORD: sipgateway_password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    restart: unless-stopped
    networks:
      - sipgateway-network

  # Optional: Redis for caching (uncomment if needed)
  # redis:
  #   image: redis:7-alpine
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data
  #   restart: unless-stopped
  #   networks:
  #     - sipgateway-network

volumes:
  mysql_data:
  # redis_data:

networks:
  sipgateway-network:
    driver: bridge 